language: python
python:
  - "3.5"

services:
  - postgresql

env:
  global:
    - APP_SETTINGS="testing"
    - CODECOV_TOKEN="0c4bd51b-2d42-4993-8a05-f486eea0af44"

install:
  - "pip install -r requirements.txt"

before_script:
  - "psql -c 'create database test_db;' -U postgres"

script:
   - python3 -m pytest -v --cov api --cov-report term-missing

after_success:
  - coveralls
  - codecov